# Generated by Django 4.2.30 on 2026-04-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('description', models.TextField()),
                ('is_education', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=300)),
                ('business_problem', models.TextField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('chatbot', 'Chatbot'), ('agent', 'AI Agent'), ('ml', 'Machine Learning'), ('web', 'Web Development'), ('media', 'AI Media'), ('workflow', 'Workflow Automation')], default='agent', max_length=50)),
                ('tools_used', models.TextField(help_text='Comma-separated list of tools')),
                ('key_features', models.TextField(help_text='Describe the key features')),
                ('role', models.TextField(help_text='Your role and contribution')),
                ('challenges', models.TextField(help_text='Biggest challenge faced')),
                ('lessons_learned', models.TextField(help_text='What you learned')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on projects page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ai', 'AI & Machine Learning'), ('web', 'Web Development'), ('data', 'Data & Analytics'), ('tools', 'Tools & Platforms'), ('soft', 'Soft Skills')], max_length=50)),
                ('proficiency', models.IntegerField(default=80, help_text='Percentage 0-100')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
