# Generated by Django 4.2.30 on 2026-04-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_problem',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(default='', help_text='Describe the key features'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.TextField(default='', help_text='Your role and contribution'),
        ),
    ]
