# Generated by Django 4.2.30 on 2026-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_business_problem_project_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, help_text='Live demo or deployed project URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('agent', 'AI Agent'), ('ml', 'Machine Learning'), ('web', 'Web Development'), ('media', 'AI Media'), ('workflow', 'Workflow Automation'), ('google_ai_studio', 'Google AI Studio Media Project')], default='agent', max_length=50),
        ),
    ]
