# Generated by Django 4.2.30 on 2026-05-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_demo_link_project_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='degree_major',
            field=models.CharField(blank=True, default='', help_text='Degree and/or major (education only)', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='gpa_honors',
            field=models.CharField(blank=True, default='', help_text='GPA or honors (education only)', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
