# Generated by Django 4.2.30 on 2026-05-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(default='Focused on AI & intelligent systems', help_text='Heading shown in the About Me section on the homepage', max_length=200)),
                ('about_bio', models.TextField(default='My work spans chatbots, AI agents, machine learning pipelines, and full-stack web applications. I believe in using technology to solve real problems — clearly, efficiently, and creatively.', help_text='Paragraph shown in the About Me section on the homepage')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Job Title'),
        ),
    ]
