# Generated by Django 4.2.30 on 2026-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_siteprofile_alter_experience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='about_tagline',
            field=models.CharField(default='Problem-solver with a passion for AI and intelligent systems.', help_text='Short tagline shown under the page title on the About page', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='about_bio',
            field=models.TextField(default='My work spans chatbots, AI agents, machine learning pipelines, and full-stack web applications. I believe in using technology to solve real problems — clearly, efficiently, and creatively.', help_text='Main bio paragraph — shown on the About page and homepage'),
        ),
    ]
