# Generated by Django 4.2.30 on 2026-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email address shown on the Contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='contact_location',
            field=models.CharField(blank=True, default='', help_text='Location shown on the Contact page (e.g. Waco, Texas)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='Full LinkedIn profile URL'),
        ),
    ]
