# Generated by Django 4.2.30 on 2026-05-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_siteprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_image',
            field=models.CharField(blank=True, default='', help_text="Filename inside static/images/ (e.g. 'campus skills swap.png')", max_length=200),
        ),
    ]
